{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ticketing.fullname" . }}-redis
  labels:
    {{- include "ticketing.labels" . | nindent 4 }}
    {{- include "ticketing.selectorLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "ticketing.selectorLabels" (dict "ctx" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ticketing.labels" . | nindent 8 }}
        {{- include "ticketing.selectorLabels" (dict "ctx" . "component" "redis") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ticketing.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          image: {{ .Values.redis.image | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["redis-server", "--save", "", "--appendonly", "no"]
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - name: redis
              containerPort: 6379
          livenessProbe:
            exec: { command: ["redis-cli", "ping"] }
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec: { command: ["redis-cli", "ping"] }
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ticketing.fullname" . }}-redis
  labels:
    {{- include "ticketing.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ticketing.selectorLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: 6379
{{- end }}
